server:
  port: 8087

spring:
  application:
    name: employment-learning
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: ${SERVICE_IP:}
  
  datasource:
    url: jdbc:mysql://localhost:3306/employment_platform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: 21491879
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example: debug